#
#       @(#)Makefile.end 1.1 94/10/31 Copyright(c) Sun Microsystems, Inc.
#
#	This Makefile.end contains dependency lines for Sundiag libraries.
#	It has to be included at the end of Makefile of each test code
#	to make sure libraries will be updated every time when their
#	source code altered.

#$(TESTLIB): $(TESTLIB_SRCS)
#	cd $(@D); $(MAKE) $(@F)
FRC:
