# @(#)Makefile.master 1.1 94/10/31 SMI

all: $(FILES)

# Stop make from treating font files as ratfor source!
.SUFFIXES:

dir=$(DESTDIR)/usr/lib/$(HERE)

install: $(FILES) FRC
	-install -d -o bin -m 755 $(dir)
	install -m 644 $(FILES) $(dir)

clean:

FRC:
