#
# @(#)Makefile 1.1 94/10/31 SMI
#
# Copyright (c) 1987 by Sun Microsystems, Inc.
#

CPPFLAGS$(TARGET_MACH) += -DLOCORE -I../../sys/common/sparc
MD_HDRS =
CSRCS =
MD_CSRC = $(CSRCS:%.c=$(ARCH)/%.c)
ASSRCS =
MD_ASSRC =
